language: go
go:
  - 1.8.3

# Don't want default ./... here:
install:
- export PATH=$GOPATH/bin:$PATH
- mkdir -p $HOME/gopath/src/k8s.io
- mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/website
- cd $HOME/gopath/src/k8s.io/website

# (1) Fetch dependencies for us to run the tests in test/examples_test.go
- pushd $GOPATH/src/k8s.io && git clone https://github.com/kubernetes/kubernetes && popd
- pushd $GOPATH/src/k8s.io/kubernetes && git checkout release-1.8 && popd

# (2) Simplified deduplication of dependencies.
- cp -L -R $GOPATH/src/k8s.io/kubernetes/vendor/ $GOPATH/src/
- rm -r $GOPATH/src/k8s.io/kubernetes/vendor/

- go get -t -v k8s.io/website/test

script:
- go test -v k8s.io/website/test
- ./verify-docs-format.sh
