language: go
go:
  - 1.8.3

# Don't want default ./... here:
install:
- export PATH=$GOPATH/bin:$PATH
- mkdir -p $HOME/gopath/src/k8s.io
- mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/kubernetes.github.io

# (1) Fetch dependencies for us to run the tests in test/examples_test.go
- go get -t -v k8s.io/kubernetes.github.io/test

# Simplified deduplication of dependencies.
- cd $GOPATH/src/k8s.io/kubernetes/
- git checkout release-1.7
- cp -L -R $GOPATH/src/k8s.io/kubernetes/vendor/ $GOPATH/src/
- rm -r $GOPATH/src/k8s.io/kubernetes/vendor/

script:
- go test -v k8s.io/kubernetes.github.io/test
- ./verify-docs-format.sh
