name: Kubernetes
title: Kubernetes
description: Production-Grade Container Orchestration
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: ""
    values:
      version: "v1.5"
      githubbranch: "v1.5.7"
      docsbranch: "release-1.5"
  -
    scope:
      path: "docs"
    values:
      layout: docwithnav
      showedit: true

permalink: pretty

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

include: [_headers]

# SEO
logo: /images/favicon.png
twitter:
  username: kubernetesio

# Tables of contents, stored in the _data folder, that control the sidebar nav
tocs:
  - docs-home
  - guides
  - tutorials
  - tasks
  - concepts
  - reference
  - tools
  - samples
  - support
