[build]
# This default build command adds the robots noindex directive to the site headers.
# It is turned off for only for the production site by using [context.master] below
# DO NOT REMOVE THIS (contact @chenopis or @sig-docs-maintainers)
publish = "public"
functions = "functions"
command = "make non-production-build"

[build.environment]
HUGO_VERSION = "0.59.1"

[context.production.environment]
HUGO_BASEURL = "https://kubernetes.io/"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "make deploy-preview"

[context.branch-deploy]
command = "make deploy-preview"

[context.master]
# This context is triggered by the `master` branch and allows search indexing
# DO NOT REMOVE THIS (contact @chenopis or @sig-docs-maintainers)
publish = "public"
command = "make production-build"
