[build]
# This default build command adds the robots noindex directive to the site headers
publish = "public"
command = "hugo --enableGitInfo && cp netlify_noindex_headers.txt public/_headers"

[context.production.environment]
HUGO_BASEURL = "https://kubernetes.io/"
HUGO_VERSION = "0.43.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.43.1"

[context.branch-deploy]
command = "hugo --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.43.1"

[context.master]
# This context is triggered by the master branch and allows search indexing 
publish = "public"
command = "hugo"
