apiVersion: v1		
 -kind: ResourceQuota		
 -metadata:		
 -  name: object-quota-demo		
 -spec:		
 -  hard:		
 -    persistentvolumeclaims: "2"		
 -    services.loadbalancers: "2"    		
 -    services.nodeports: "0" 
