apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  primary.cnf: |
    # 僅在主伺服器上應用此設定
    [mysqld]
    log-bin
  replica.cnf: |
    # 僅在副本伺服器上應用此設定
    [mysqld]
    super-read-only

